### ISSUE TITLE
viewport.bounds returns illegal coordinate sets for large dimensions

### ISSUE THREAD

**Issue by coopy** [mapbox/geo-viewport#34]
`bounds` returns an illegal "top left" coordinate set (`minX < -180`) when the first member of the `dimensions` array passed in is larger than a certain threshold. This happens for valid `viewport` (centerpoint) coordinates.

We found this bug when a call to the mapbox geocoding API was returning an error: `BBox minX value must be a number between -180 and 180`. The minX value was less than -180, and was coming from the `geo-viewport` `bounds` function.

Example arguments that cause the bug: `viewport.bounds([-98.5556199, 39.8097343], 3, [2892, 480], 512)`
Bounds returned: `[ -225.615234375, 21.861498734372567, 28.564453125, 54.1109429427243 ]`

Failing test case available here: https://github.com/mapbox/geo-viewport/compare/master...coopy:geo-viewport:master#diff-9d2f3f2a83cca94e2e2185c0173c9170a80fdd3428bdf1c6f580f9d23f2fbe01R133

**Comment by dereekb** [comment]
The longitude of the map's bounds can be greater than 180 (or less than -180). It will occur when the map is stretched and you can see multiple maps. Here's a visual example:

![Screen Shot 2022-09-05 at 2 32 19 AM](https://user-images.githubusercontent.com/3586580/188393549-4929c7a1-6c73-42de-8647-9279e53d8057.png)

In your input it looks like the X/width of the canvas is 2892px, which would correspond to the top left corner's latitude being at -225.61, which is correct even if it isn't technically a valid longitude value.

If I'm understand correctly, you passed the direct output of the bounds to the API and it gave you that error?

You'll want to cap or wrap the values for these cases.

**Comment by coopy** [comment]
Thank you for the detailed answer – that makes sense, though it wasn't immediately intuitive. I no longer have access to the code that produced this issue, but perhaps the call I was making to `bounds` happened before zoom level was set, and the map was "repeated" like in your example.

Since `bounds` usage together with the geocode API is likely common, a note in both sets of docs to encourage clamping could be helpful.

Closing!
