### ISSUE TITLE
Ruby port

### ISSUE THREAD

**Issue by timiyay** [mapbox/geo-viewport#6]
Is there any community or Mapbox interest in a Ruby port of this library, and the underlying `node-sphericalmercator` library?

I've already ported it to a Ruby project, including the existing test suites. If anyone is into it, I can publish it as a Rubygem. Ideally, it would be maintained by Mapbox, but it wouldn't kill me to maintain it myself (if this repo is still alive).

I've been using it in a JS client for deriving the geographic bounding box for static maps that I request from the Mapbox Static Image API. We're adding endpoints to our Ruby API that allow us to spatially-query data using the same geo bbox as the underlying static map.

**Comment by tmcw** [comment]
👍 happy to link it from this repo. Unfortunately can't offer to maintain another library, both because... I maintain way too many... and since Mapbox is mostly a JS/C++/Python shop, there isn't much other-than-me capacity to do so.
